server:
  port: 8082

spring:
  application:
    name: fitness-service
  cloud:
    stream:
      function:
        definition: consumeFitnessEvent
      bindings:
        consumeFitnessEvent-in-0:
          destination: fitness-events